### ISSUE TITLE
Light Mode support/Transparency Effects removal

### ISSUE THREAD

**Issue by DalgleishGX** [TakosThings/Fluent-Discord#281] opened 2024-03-24 21:12 UTC
I'd love to use this but sadly I find two issues with it. Issues are the inability to disable transparency effects and the lack of Light mode support.

It'd be awesome to have these features added so the theme becomes more versatile and more user friendly.

**Comment by TakosThings** [comment] 2024-03-26 07:14
Duplicate of #247

**Closed as not planned by TakosThings** 2024-03-26 07:14 UTC
Labels: duplicate, enhancement
