### ISSUE TITLE
MessageLoggerV2 Log Icon Not Showing

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#178] opened 2022-08-23 02:56 UTC
**Describe the bug**
With the theme, the icon to open logs on MessageLoggerV2 will not show, but the button is still clickable and functions normally, even complying with the Fluent Discord UI. I couldn't make this a plugin request as it isn't on the BetterDiscord website.

**Screenshots**
![image](https://user-images.githubusercontent.com/45770865/186059367-f33d1631-1fd9-4ad5-9dcd-d087d34357dd.png)

**Comment by TakosThings** [comment] 2022-08-23 10:19
Duplicate of #34

**Closed as completed by TakosThings** 2022-08-23 10:19 UTC
Labels: bug, duplicate, wontfix
