### ISSUE TITLE
theme is broken in betterdiscord

### ISSUE THREAD

**Issue by foursplaysroblox** [TakosThings/Fluent-Discord#264] opened 2023-10-28 11:28 UTC
**Describe the bug**
Only the plugins and theme library are kinda themed

**Screenshots**
![image](https://github.com/TakosThings/Fluent-Discord/assets/82078139/7e1c9631-2716-4f66-89f5-95187522b3f0)

**Comment by TakosThings** [comment] 2023-10-28 11:30
Duplicate of #258

**Closed by TakosThings** 2023-10-28 11:30 UTC
Labels: bug, duplicate
