### ISSUE TITLE
version stuck at 1.3.0 even with new updates

### ISSUE THREAD

**Issue by cmdshft** [TakosThings/Fluent-Discord#156] opened 2022-07-18 05:48 UTC
https://user-images.githubusercontent.com/8571823/179451673-2a7d0fd6-dac5-4dbe-9c21-628a6a8ee6c5.mp4

**Comment by TakosThings** [comment] 2022-07-18 06:56
Duplicate of #107

**Closed as completed by TakosThings** 2022-07-18 06:56 UTC
Labels: bug, duplicate
