### ISSUE TITLE
"Unread messages" prompt overflows on voice chats and threads

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#148] opened 2022-07-10 02:33 UTC
**Describe the bug**
On text channels of corresponding voice channels and threads, the "unread message" prompt will overflow, not sizing correctly to the screen.

**Screenshots**
![Screenshot 2022-07-09 213043](https://user-images.githubusercontent.com/45770865/178128975-56cf81c7-6929-45c1-b597-93b10ccdaed8.jpg)

**Comment by TakosThings** [comment] 2022-07-10 02:38
Duplicate of #145

**Closed as completed by TakosThings** 2022-07-10 02:38 UTC
Labels: bug, duplicate
