### ISSUE TITLE
Custom Status buttons are invisible.

### ISSUE THREAD

**Issue by GalaxinTM** [TakosThings/Fluent-Discord#310] opened 2024-10-12 21:12 UTC
**Describe the bug**
The buttons for clearing and editing my status are not visible when the theme is active.

**Screenshots**
Left: Theme on. | Right: Theme off
![image](https://github.com/user-attachments/assets/9faa623e-93e0-48d3-a790-c00645f3fef9) ![image](https://github.com/user-attachments/assets/301d4749-b897-4b72-a6a4-fbadd6b7412a)

**Comment by TakosThings** [comment] 2024-10-20 02:28
Duplicate of #306

**Closed as not planned by TakosThings** 2024-10-20 02:28 UTC
Labels: bug, duplicate
