### ISSUE TITLE
Broken Icons For Channel With No Permissions

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#37] opened 2022-02-20 08:37 UTC
![image](https://user-images.githubusercontent.com/94354651/154834945-8d745ee0-aba8-4b23-91e2-5fea32045acf.png)
if i have no perms this happens

**Comment by TakosThings** [comment] 2022-02-20 08:45
Duplicate of #31 and already fixed in b2164272e23003c2915ac5fc7622a315591e5476

**Closed as completed by TakosThings** 2022-02-20 08:45 UTC
Labels: duplicate

**Comment by khaledmoayad** [comment] 2022-02-20 08:56
No, no. 31 is for a missing stream icon, but this is for cam and stream

**Comment by khaledmoayad** [comment] 2022-02-20 08:56
+ its not missing; they're just bugged
