### ISSUE TITLE
Scrolling in a server with a lot of channels

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#239] opened 2023-05-25 20:05 UTC
This will cause all the channels to shift to left eventually (50+ channels?)

**Comment by Esterze** [comment] 2023-05-25 20:06
![image](https://github.com/TakosThings/Fluent-Discord/assets/97387354/6d423eb8-db41-4d76-a760-9cc219195059)
![image](https://github.com/TakosThings/Fluent-Discord/assets/97387354/20f1e6ad-1dcb-49d0-948a-8970dc1cf5a9)

**Comment by TakosThings** [comment] 2023-07-07 16:46
This is caused by lazy loading which can't be fixed in the theme. Only workaround is to mute channels you don't need

**Closed as completed by TakosThings** 2023-07-07 16:46 UTC
Labels: bug
