### ISSUE TITLE
Saving animation is not properly aligned

### ISSUE THREAD

**Issue by christianavi** [TakosThings/Fluent-Discord#46] opened 2022-03-04 13:04 UTC
When saving some settings, the animation on the Save button is not properly centered.

**Screenshots**
![image](https://user-images.githubusercontent.com/43099141/156768215-e7ff783b-f9dc-45d4-b61a-c660c4559953.png)

**Comment by TakosThings** [comment] 2022-03-04 13:08
Duplicate of #42

**Closed as completed by TakosThings** 2022-03-04 13:08 UTC
Labels: bug, duplicate
