### ISSUE TITLE
Fix the theme due to the newest Discord update that broke every custom theme on Vencord.

### ISSUE THREAD

**Issue by 5gdev** [TakosThings/Fluent-Discord#266] opened 2023-10-30 15:47 UTC
Read the title.

**Comment by im-h** [comment] 2023-10-31 05:47
https://github.com/TakosThings/Fluent-Discord/issues/258#issuecomment-1779053607

**Comment by TakosThings** [comment] 2023-10-31 08:33
> Read the title.

Read the pinned issue.

Duplicate of #258

**Closed as not planned by TakosThings** 2023-10-31 08:33 UTC
Labels: bug, duplicate
