### ISSUE TITLE
Theme stopped working in vencord

### ISSUE THREAD

**Issue by IdanKahan** [TakosThings/Fluent-Discord#268] opened 2023-11-03 14:58 UTC
The theme stopped working in vencord

**Comment by im-h** [comment] 2023-11-03 21:00
Read the pinned issue.

Duplicate of https://github.com/TakosThings/Fluent-Discord/issues/258

**Comment by TakosThings** [comment] 2023-11-07 06:40
Duplicate of #258

**Closed as not planned by TakosThings** 2023-11-07 06:40 UTC
Labels: bug, duplicate
