### ISSUE TITLE
Themes got broken after last discord update

### ISSUE THREAD

**Issue by Neekodesu** [TakosThings/Fluent-Discord#263] opened 2023-10-26 19:20 UTC
Basically that, themes got broken after last update and in vencord they are saying that we should contact theme developers to fix it in order to use themes.

**Comment by yippii** [comment] 2023-10-27 04:11
#258 replicate

> Update 2023-10-25: Discord pushed out a bunch of breaking changes, BD will need to update first before I can fix the theme

**Comment by Neekodesu** [comment] 2023-10-27 05:40
![image](https://github.com/TakosThings/Fluent-Discord/assets/47283957/2f46c002-da14-49f7-9978-82b04b5f64bd)

**Comment by Neekodesu** [comment] 2023-10-27 05:58
Also could you add a link to .css in order to use it with vencord? Would be great! Ty

**Comment by gk98s** [comment] 2023-10-27 14:49
> Also could you add a link to .css in order to use it with vencord? Would be great! Ty

just go to releases and rather than downloading the css file right click it and copy link and that will work once the theme is fixed

**Comment by TakosThings** [comment] 2023-10-28 00:37
Duplicate of #258

**Closed as not planned by TakosThings** 2023-10-28 00:37 UTC
Labels: bug, duplicate
