### ISSUE TITLE
Bigger server icons

### ISSUE THREAD

**Issue by ZekyTheWolf** [TakosThings/Fluent-Discord#250] opened 2023-07-26 15:01 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make possible to set bigger server icons without breaking whole theme.

**Additional context**
There is a options that can set bigger server icons, but eventually it will break whole theme, so make possible to set bigger icons without breaking theme would be nice.

**Comment by TakosThings** [comment] 2023-08-21 13:16
Duplicate of #219 

Updated [FAQ](https://github.com/TakosThings/Fluent-Discord/wiki/FAQ#can-i-make-the-server-icons-bigger) entry on this.

**Closed as not planned by TakosThings** 2023-08-21 13:16 UTC
Labels: enhancement
