### ISSUE TITLE
User Popout Broken

### ISSUE THREAD

**Issue by Flonky** [TakosThings/Fluent-Discord#191] opened 2022-10-18 23:23 UTC
**Describe the bug**
The current user pop out is mostly broken

**Screenshots**
![image](https://user-images.githubusercontent.com/64008721/196563100-4cc675bd-cee5-4bf6-bd4b-1b8f42af853a.png)

**Comment by TakosThings** [comment] 2022-10-19 08:08
Duplicate of #181 

Any work on user profiles is on hold until the new design is made generally available

**Closed as not planned by TakosThings** 2022-10-19 08:08 UTC
Labels: bug
