### ISSUE TITLE
Theme Not support UTF-8

### ISSUE THREAD

**Issue by jooo8594** [TakosThings/Fluent-Discord#217] opened 2023-03-12 13:43 UTC
**Describe the bug**

**Screenshots**

**Comment by jooo8594** [comment] 2023-03-12 13:45
![image](https://user-images.githubusercontent.com/50031064/224548719-9f2d5d34-ccab-4e5b-a154-63cf5f4fd1d2.png)

**Comment by TakosThings** [comment] 2023-03-13 07:57
You need to complete the template and describe what the issue is otherwise this will be marked as invalid.

**Comment by jooo8594** [comment] 2023-03-13 10:20
The problem is that some server names in Discord that are written other than English are confused, such as the Arabic language in the picture, because the Arabic language in programming depends on UTF-8, otherwise it may come in the form of squares or strange or similar words

**Comment by jooo8594** [comment] 2023-03-13 10:23
The advantage in UTF-8 in programming makes the text support most of the world's languages

**Comment by jooo8594** [comment] 2023-03-13 10:28
![image](https://user-images.githubusercontent.com/50031064/224675641-0581b56c-4468-4763-a553-db7a4f521adc.png)
The problem lies in the name of the server from the inside and also the name of the room in the bar

**Closed as not planned** 2023-03-14 17:33 UTC
Labels: bug, further info required
